# Generated by Django 3.2.19 on 2024-05-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('productdescription1', models.CharField(max_length=200)),
                ('productdescription2', models.CharField(max_length=200)),
                ('productnumber', models.IntegerField()),
                ('productimage', models.URLField()),
            ],
        ),
    ]
