# Generated by Django 3.2.19 on 2024-05-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webquicky', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Product',
        ),
    ]
